apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zygomorphic-haddock-java-quarkus
  janus-idp.io/tekton: zygomorphic-haddock-java-quarkus
  backstage.io/kubernetes-id: zygomorphic-haddock-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zygomorphic-haddock-java-quarkus
resources: 
- deployment.yaml
- route.yaml
- service.yaml
